export const TYPE = {
    STUDENT: 'STUDENT_TYPE',
    TEACHER: 'TEACHER_TYPE',
    TEAM: 'TEAM_TYPE',
    TOPIC: 'TOPIC_TYPE',
    DEADLINE: 'DEALINE_TYPE',
    MYTOPIC: 'MYTOPIC_TYPE',
    ACCOUNT: 'ACCOUNT_TYPE'

}